baseurl = "/"
title = "OpenForecast"
author = "Ivan Svetunkov"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "OpenForecast"
  description = "Forecasting using open source software"
  
  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  # path to the favicon, under "static"
  favicon = "favicon.ico"

  [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1
[[menu.main]]
    name = "ADAM"
    url = "/adam/"
    weight = 2
[[menu.main]]
    name = "smooth"
    url = "https://forecasting.svetunkov.ru/en/category/r-en/smooth/"
    weight = 3
[[menu.main]]
    name = "greybox"
    url = "https://forecasting.svetunkov.ru/en/category/r-en/greybox/"
    weight = 4
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/iSvetunkov"
    weight = 5
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 6
