baseurl = "/"
languageCode = "en-us"
title = "OpenForecast: Open source forecating for everyone"
theme = "hugo-theme-pure"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    identifier = "about"
    title = "About"
    name = "About"
    url = "/about/"
[[menu.main]]
    identifier = "posts"
    title = "Posts"
    name = "Posts"
    url = "/post/"
[[menu.main]]
    identifier = "twitter"
    title = "Twitter"
    name = "Twitter"
    url = "https://twitter.com/iSvetunkov"

[taxonomies]
    category = "categories"
    tag = "tags"
    series = "series"

[params]
    description = "OpenForecast, open source forecating for everyone"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml", "python"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

    dateFormatToUse = "2006-01-02"
    mainSections = "posts"
    enableMathJax = true
    
    [params.profile]
        enabled = false
        
    [params.site.logo]
        enabled = true
        width = 40
        height = 40
        url = "favicon.ico"
        
    [params.site]
    title = "OpenForecast"
    favicon = "favicon.ico"
    board = "<p>enjoy~</p>"
