baseurl = "/"
languageCode = "en-us"
title = "OpenForecast"
author = "Ivan Svetunkov"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "ADAM"
    url = "/adam/"
    weight = 1
[[menu.main]]
    name = "SBA"
    url = "/sba/"
    weight = 2
[[menu.main]]
    name = "Papers"
    url = "/papers.html"
    weight = 3
[[menu.main]]
    name = "smooth"
    url = "https://forecasting.svetunkov.ru/en/category/r-en/smooth/"
    weight = 4
[[menu.main]]
    name = "greybox"
    url = "https://forecasting.svetunkov.ru/en/category/r-en/greybox/"
    weight = 5
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/iSvetunkov"
    weight = 6
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/isvetunkov/"
    weight = 7
[[menu.main]]
    name = "Homepage"
    url = "https://forecasting.svetunkov.ru"
    weight = 8
    
[params]
  sitename = "OpenForecast"
  description = "Forecasting using open source software"
  
  # options for highlight.js (version, additional languages, and theme)
  highlightjsVersion = "9.12.0"
  highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
  highlightjsLang = ["r", "yaml"]
  highlightjsTheme = "github"

  MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
  MathJaxVersion = "2.7.5"

  # path to the favicon, under "static"
  favicon = "favicon.ico"

  [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
